servers:
    '443869685054701569':
        name: The Realm
        channels:
        - bot-commands
        - command-line
        defaultChannel:
          bot-commands
        greetingChannel:
          portal
        generators:
        - potion
        - wand
        - summon
        validRoles:
            Dwarf:
                secondaryRoles:
                    - Humanoids
            Elf:
                secondaryRoles:
                    - Humanoids
            Fairy:
                secondaryRoles:
                    - Humanoids
            Goblin:
                secondaryRoles:
                    - Humanoids
            Gnome:
                secondaryRoles:
                    - Humanoids
            Halfling:
                secondaryRoles:
                    - Humanoids
            Human:
                secondaryRoles:
                    - Humanoids
            Mermaid:
                secondaryRoles:
                    - Humanoids
            Vampire:
                secondaryRoles:
                    - Humanoids
            Werewolf:
                secondaryRoles:
                    - Humanoids
            Witch:
                secondaryRoles:
                    - Humanoids
            Wizard:
                secondaryRoles:
                    - Humanoids
            Zombie:
                secondaryRoles:
                    - Humanoids
            
            Basilisk:
                secondaryRoles:
                    - Beasts
            Chimera:
                secondaryRoles:
                    - Beasts
            Centaur:
                secondaryRoles:
                    - Beasts
            Cyclops:
                secondaryRoles:
                    - Beasts
            Dragon:
                secondaryRoles:
                    - Beasts
            Gryphon:
                secondaryRoles:
                    - Beasts
            Loch Ness Monster:
                secondaryRoles:
                    - Beasts
            Ogre:
                secondaryRoles:
                    - Beasts
            Pegasus:
                secondaryRoles:
                    - Beasts
            Phoenix:
                secondaryRoles:
                    - Beasts
            Sasquatch:
                secondaryRoles:
                    - Beasts
            Sphinx:
                secondaryRoles:
                    - Beasts
            Unicorn:
                secondaryRoles:
                    - Beasts
            
            Angel:
                secondaryRoles:
                    - Spirits
            Banshee:
                secondaryRoles:
                    - Spirits
            Demon:
                secondaryRoles:
                    - Spirits
            Deity:
                secondaryRoles:
                    - Spirits
            Djinn:
                secondaryRoles:
                    - Spirits
            Ghost:
                secondaryRoles:
                    - Spirits
            Ghoul:
                secondaryRoles:
                    - Spirits
            Grim:
                secondaryRoles:
                    - Spirits
            Kobold:
                secondaryRoles:
                    - Spirits
            Poltergeist:
                secondaryRoles:
                    - Spirits
            Skeleton:
                secondaryRoles:
                    - Spirits
            Sylph:
                secondaryRoles:
                    - Spirits
            Wraith:
                secondaryRoles:
                    - Spirits
        removeOnUpdate:
        - Beasts
        - Spirits
        - Humanoids
        strings:
          roleChange:
            '{0.author.mention}, you are now a {1}.'
          invalidRole:
            '{0.author.mention}, role {1} is not on the valid list. Perhaps have a look at my bestiary with !list, or I can choose for you with !rerole .'
          welcome:
            'Welcome to {0.name}, {1.mention}. You seem to be a ... {2.name}, perhaps?
            
My crystal ball has been foggy of late. If I''m wrong, quest to the pinned message in {3.mention} to change your character, adventurer!'
          diceResults:
            '{0.author.mention}, the fates have spoken: {1}, for a total of {2}.'
          roleList:
            'Have a look at my bestiary. You may be one of these, just say "!role rolename".'
          rerole:
            'Another peek at my crystal ball... {0.author.mention}, are you perhaps a {1.name}?'
        urls:
          roleImage:
            'https://cdn.discordapp.com/attachments/445271158502457345/490208979767656478/The_Realm_Roles1.png'
    '489197880809095168':
        name: test server
        channels: 
        - bot-commands
        defaultChannel:
          bot-commands
        greetingChannel:
          portal
        generators:
        - potion
        - wand
        - summon
        validRoles:
            Dwarf:
                secondaryRoles:
                    - Humanoids
            Elf:
                secondaryRoles:
                    - Humanoids
            Fairy:
                secondaryRoles:
                    - Humanoids
            Goblin:
                secondaryRoles:
                    - Humanoids
            Gnome:
                secondaryRoles:
                    - Humanoids
            Halfling:
                secondaryRoles:
                    - Humanoids
            Human:
                secondaryRoles:
                    - Humanoids
            Mermaid:
                secondaryRoles:
                    - Humanoids
            Vampire:
                secondaryRoles:
                    - Humanoids
            Werewolf:
                secondaryRoles:
                    - Humanoids
            Witch:
                secondaryRoles:
                    - Humanoids
            Wizard:
                secondaryRoles:
                    - Humanoids
            Zombie:
                secondaryRoles:
                    - Humanoids
            
            Basilisk:
                secondaryRoles:
                    - Beasts
            Chimera:
                secondaryRoles:
                    - Beasts
            Centaur:
                secondaryRoles:
                    - Beasts
            Cyclops:
                secondaryRoles:
                    - Beasts
            Dragon:
                secondaryRoles:
                    - Beasts
            Gryphon:
                secondaryRoles:
                    - Beasts
            Loch Ness Monster:
                secondaryRoles:
                    - Beasts
            Ogre:
                secondaryRoles:
                    - Beasts
            Pegasus:
                secondaryRoles:
                    - Beasts
            Phoenix:
                secondaryRoles:
                    - Beasts
            Sasquatch:
                secondaryRoles:
                    - Beasts
            Sphinx:
                secondaryRoles:
                    - Beasts
            Unicorn:
                secondaryRoles:
                    - Beasts
            
            Angel:
                secondaryRoles:
                    - Spirits
            Banshee:
                secondaryRoles:
                    - Spirits
            Demon:
                secondaryRoles:
                    - Spirits
            Deity:
                secondaryRoles:
                    - Spirits
            Djinn:
                secondaryRoles:
                    - Spirits
            Ghost:
                secondaryRoles:
                    - Spirits
            Ghoul:
                secondaryRoles:
                    - Spirits
            Grim:
                secondaryRoles:
                    - Spirits
            Kobold:
                secondaryRoles:
                    - Spirits
            Poltergeist:
                secondaryRoles:
                    - Spirits
            Skeleton:
                secondaryRoles:
                    - Spirits
            Sylph:
                secondaryRoles:
                    - Spirits
            Wraith:
                secondaryRoles:
                    - Spirits
        removeOnUpdate:
        - Beasts
        - Spirits
        - Humanoids
        strings:
          roleChange:
            '{0.author.mention}, you are now a {1}.'
          invalidRole:
            '{0.author.mention}, role {1} is not on the valid list.'
          welcome:
            'Welcome to {0.name}, {1.mention}. You seem to be a ... {2.name}, perhaps?

My crystal ball has been foggy of late. If I''m wrong, quest to the pinned message in {3.mention} to change your character, adventurer!'
          diceResults:
            '{0.author.mention}, the fates have spoken: {1}, for a total of {2}.'
          roleList:
            'Have a look at my bestiary. You may be one of these, just say "!role rolename".'
          rerole:
            'Another peek at my crystal ball... {0.author.mention}, are you perhaps a {1.name}?'
        urls:
          roleImage:
            'https://cdn.discordapp.com/attachments/445271158502457345/490208979767656478/The_Realm_Roles1.png'
