servers:
  default: &defaults
    channels:
    - bot-commands
    greetingChannel:
      portal
    generators:
    - creature
    - potion
    - wand
    - name
    - loot
    - encounter
    strings: &defaultStrings
      roleChange:
        '{0}, you are now a {1}.'
      roleClear:
        '{0}, your {1} has been cleared.'
      diceResults:
        '{0}, the fates have spoken: {1}, for a total of {2}.'
      rerole:
        'Another peek at my crystal ball... {0}, are you perhaps a {1}?'
  '443869685054701569': &realm
    name: The Realm
    channels:
    - bot-commands
    - command-line
    - tourney
    defaultRoleset: creature
    rolesets:
      creature:
        Dwarf:
          secondaryRoles:
          - Humanoids
        Elf:
          secondaryRoles:
          - Humanoids
        Fairy:
          secondaryRoles:
          - Humanoids
        Giant:
          secondaryRoles:
          - Humanoids
        Goblin:
          secondaryRoles:
          - Humanoids
          random: False
        Gnome:
          secondaryRoles:
          - Humanoids
        Halfling:
          secondaryRoles:
          - Humanoids
        Human:
          secondaryRoles:
          - Humanoids
        Mermaid:
          secondaryRoles:
          - Humanoids
          random: False
        Vampire:
          secondaryRoles:
          - Humanoids
        Werewolf:
          secondaryRoles:
          - Humanoids
        Witch:
          secondaryRoles:
          - Humanoids
          random: False
        Wizard:
          secondaryRoles:
          - Humanoids
          random: False
        Zombie:
          secondaryRoles:
          - Humanoids

        Basilisk:
          secondaryRoles:
          - Beasts
        Chimera:
          secondaryRoles:
          - Beasts
        Centaur:
          secondaryRoles:
          - Beasts
        Cyclops:
          secondaryRoles:
          - Beasts
        Dragon:
          secondaryRoles:
          - Beasts
        Gryphon:
          secondaryRoles:
          - Beasts
        Loch Ness Monster:
          secondaryRoles:
          - Beasts
        Ogre:
          secondaryRoles:
          - Beasts
          random: False
        Orc:
          secondaryRoles:
          - Beasts
          random: False
        Pegasus:
          secondaryRoles:
          - Beasts
        Phoenix:
          secondaryRoles:
          - Beasts
        Sasquatch:
          secondaryRoles:
          - Beasts
          random: False
        Sphinx:
          secondaryRoles:
          - Beasts
        Unicorn:
          secondaryRoles:
          - Beasts

        Angel:
          secondaryRoles:
          - Spirits
        Ascended:
          secondaryRoles:
          - Spirits
        Banshee:
          secondaryRoles:
          - Spirits
          random: False
        Demon:
          secondaryRoles:
          - Spirits
        Deity:
          secondaryRoles:
          - Spirits
        Djinn:
          secondaryRoles:
          - Spirits
        Ghost:
          secondaryRoles:
          - Spirits
        Ghoul:
          secondaryRoles:
          - Spirits
        Grim:
          secondaryRoles:
          - Spirits
        Kobold:
          secondaryRoles:
          - Spirits
        Poltergeist:
          secondaryRoles:
          - Spirits
        Skeleton:
          secondaryRoles:
          - Spirits
        Sylph:
          secondaryRoles:
          - Spirits
        Wraith:
          secondaryRoles:
          - Spirits
        removeOnUpdate:
        - Beasts
        - Spirits
        - Humanoids
      class:
        Barbarian:
          description: A warrior from the wilds who draws strength from his rage.
        Bard:
          description: A performer of such skill that their performances can have magical effects.
        Brawler:
          description: A fighter who relies on brawn and street smarts rather than grueling training.
        Cleric:
          description: A priest of a specific deity or pantheon. Best known for their healing magic.
        Druid:
          description: A magic user deeply in tune with nature. Can often transform into animals.
        Fighter:
        Mage:
          description: A skilled magic user who has studied or been granted the arcane arts.
        Monk:
          description: An agile warrior trained in the martial arts of a faraway land.
        Paladin:
          description: A holy knight, gifted with both physical prowess and holy magic.
        Ranger:
          description: A tracker, hunter, and/or woodsman. May know some relevant magic.
        Rogue:
          description: A thief or assassin. Quick, sneaky, and best not let out of your sight.
        Soldier:
          description: A disciplined warrior accustomed to fighting together with their comrades-in-arms.
        Sorceror:
        Warlock:
    strings:
      invalidcreature:
        '{0}, role {1} is not on the valid list. Perhaps have a look at my bestiary with `!creature`, or I can choose for you with `!rerole`.'
      invalidclass:
        '{0}, role {1} is not on the valid list. You can see the options with `!class`.'
      welcome:
        'Welcome to The Realm, {0}. You seem to be a ... {1}, perhaps? My crystal ball has been foggy of late. If I''m wrong, quest to the pinned message in <#445271158502457345> to change your character, adventurer!'
      creatureRoleList:
        'Have a look at my bestiary. You may be one of these, just say `!creature creaturename`. For instance, `!creature dragon`'
      classRoleList:
        'Looking for a career change, eh? {0}... Take your pick of these with `!class classname`. For instance, `!class soldier`'
      <<: *defaultStrings
    static:
      spank: https://i.imgur.com/3ZERxgc.png
      charge: https://cdn.discordapp.com/attachments/444030298406125568/503820387864281089/annoyedcatTim2.png
    scheduled:
    - time: 2018-12-31T02:00
      channel: announcements
      message: The new year begins! The first places to celebrate 2019 are Kiritimati and Samoa!
    - time: 2018-12-31T03:00
      channel: announcements
      message: Happy New Year to Antarctica's McMurdo Station!
    - time: 2018-12-31T04:00
      channel: announcements
      message: 2019 has reached a continental mainland! It's now the new year in Russia's Kamchatka Time zone!
    - time: 2018-12-31T05:00
      channel: announcements
      message: Happy New Year to our Aussie friends in New South Wales and Victoria! This includes Sydney, Melbourne, Canberra, and Newcastle!
    - time: 2018-12-31T05:30
      channel: announcements
      message: Happy New Year to our friends in Adelaide!
    - time: 2018-12-31T06:00
      channel: announcements
      message: Happy New Year to our friends in Guam, Papua New Guinea, and Brisbane, Australia!
    - time: 2018-12-31T06:30
      channel: announcements
      message: Happy New Year to our friends in Darwin!
    - time: 2018-12-31T07:00
      channel: announcements
      message: Happy New Year to our friends in Tokyo and Seoul!
    - time: 2018-12-31T08:00
      channel: announcements
      message: Happy New Year to our friends in Perth, Singapore, the Philippines, Taiwan, and all of China!
    - time: 2018-12-31T09:00
      channel: announcements
      message: Happy New Year to our friends in Vietnam, Thailand, and Indonesia!
    - time: 2018-12-31T09:30
      channel: announcements
      message: Happy New Year to our friends in Myanmar!
    - time: 2018-12-31T10:00
      channel: announcements
      message: Happy New Year to our friends in Bangladesh, Kazakhstan, and Kyrgyzstan!
    - time: 2018-12-31T10:15
      channel: announcements
      message: Happy New Year to our friends in Nepal!
    - time: 2018-12-31T10:30
      channel: announcements
      message: Happy New Year to our friends in India and Sri Lanka!
    - time: 2018-12-31T11:00
      channel: announcements
      message: Happy New Year to our friends in Pakistan, the Maldives, and Uzbekistan!
    - time: 2018-12-31T11:30
      channel: announcements
      message: Happy New Year to our friends in Afghanistan!
    - time: 2018-12-31T12:00
      channel: announcements
      message: Happy New Year to our friends in Armenia, Georgia, and Dubai!
    - time: 2018-12-31T12:30
      channel: announcements
      message: Happy New Year to our friends in Iran!
    - time: 2018-12-31T13:00
      channel: announcements
      message: Happy New Year to our friends in Turkey, Saudi Arabia, Qatar, Yemen, Madagascar, Kenya, Uganda, and Moscow!
    - time: 2018-12-31T14:00
      channel: announcements
      message: Happy New Year to our friends in Jordan, Egypt, South Africa, Greece, Ukraine, Israel, and Palestine!
    - time: 2018-12-31T15:00
      channel: announcements
      message: Happy New Year to our friends in Belgium, the Netherlands, Croatia, Germany, France, Spain, Italy, Sweden, Norway, Morocco, Nigeria, and EVE Online!
    - time: 2018-12-31T16:00
      channel: announcements
      message: Happy New Year to our friends in the United Kingdom, Portugal, Ireland, Liberia, Mali, Iceland, and the International Space Station!
    - time: 2018-12-31T18:00
      channel: announcements
      message: Happy New Year to our friends in Sao Paulo and other parts of Brazil!
    - time: 2018-12-31T19:00
      channel: announcements
      message: Happy New Year to our friends in Argentina and most of Greenland and Brazil!
    - time: 2018-12-31T19:30
      channel: announcements
      message: Happy New Year to our friends in Newfoundland!
    - time: 2018-12-31T20:00
      channel: announcements
      message: Happy New Year to our friends in Venezuela, the Dominican Republic, and Barbados!
    - time: 2018-12-31T21:00
      channel: announcements
      message: Happy New Year to our friends in New York, Toronto, Montreal, Atlanta, Cuba, Jamaica, Chile, and the Bahamas!
    - time: 2018-12-31T22:00
      channel: announcements
      message: Happy New Year to our friends in Mexico City, Chicago, Winnipeg, Nashville, Belize, and Honduras!
    - time: 2018-12-31T23:00
      channel: announcements
      message: Happy New Year to our friends in Edmonton, Denver, Phoenix, and Mazatlan!
    - time: 2019-01-01T00:00
      channel: announcements
      message: Happy New Year to our friends in Sacramento, Seattle, Modesto, San Francisco, and Vancouver!
    - time: 2019-01-01T01:00
      channel: announcements
      message: Happy New Year to our friends in Alaska!
    - time: 2019-01-01T02:00
      channel: announcements
      message: Happy New Year to our friends in Hawaii and Alaska's Aleutian Islands!
    - time: 2019-01-01T03:00
      channel: announcements
      message: Happy New Year to our friends in American Samoa and Niue!
    - time: 2019-01-01T04:00
      channel: announcements
      message: '2018 is officially over! If you had an IEEE 802 ballot with an "Anywhere on Earth" deadline, the deadline has now passed!'
    - time: 2018-12-30T12:00
      channel: command-line
      message: This is a test message to confirm that the New Years messages are set up correctly. It should appear in the command-line channel at noon PST on December 30.
    <<: *defaults
  '489197880809095168':
    <<: *realm
  '494373430637101058':
    name: Test
    defaultRoleset:
      element
    rolesets:
      element:
        Solar:
        Lunar:
        Gaian:
      job:
        Soldier:
        Mage:
        Archer:
    strings:
      welcome:
        'Welcome, {0}. You have an aura of {1} magic around you. If you''d like to change it, see the pinned message in <#494374610545147905>.'
      elementRoleList:
        'The elements are as follows: {0}. You may choose your alignment with "!element elementname".'
      jobRoleList:
        'The jobs are as follows: {0}. You may choose your job with "!job jobname".'
      rerole:
        'Another peek at my crystal ball... {0}, are you attuned to {1} magic?'
      <<: *defaultStrings
    <<: *defaults
